CREATE TABLE [dbo].[BENEFICIARIOS] (
    [ID]        BIGINT       IDENTITY (1, 1) NOT NULL,
    [CPF]       VARCHAR (11) NOT NULL,
    [NOME]      VARCHAR (50) NOT NULL,
    [IDCLIENTE] BIGINT       NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);
GO;
ALTER TABLE [dbo].[BENEFICIARIOS]
ADD CONSTRAINT FK_BENEFICIARIOS_CLIENTES FOREIGN KEY (IDCLIENTE) REFERENCES dbo.CLIENTES(ID);
GO;