ALTER PROCEDURE FI_SP_ConsBeneficiario
    @IDCLIENTE BIGINT = NULL,
    @ID BIGINT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF @ID IS NULL AND @IDCLIENTE IS NULL
    BEGIN
        SELECT NOME, CPF, IDCLIENTE, ID 
        FROM BENEFICIARIOS WITH(NOLOCK);
    END
    ELSE IF @IDCLIENTE IS NULL AND @ID IS NOT NULL
    BEGIN
        SELECT NOME, CPF, IDCLIENTE, ID 
        FROM BENEFICIARIOS WITH(NOLOCK) 
        WHERE ID = @ID;
    END
    ELSE
    BEGIN
        SELECT NOME, CPF, IDCLIENTE, ID 
        FROM BENEFICIARIOS WITH(NOLOCK) 
        WHERE IDCLIENTE = @IDCLIENTE;
    END
END;
