ALTER PROC FI_SP_ConsCliente
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT c.NOME, c.SOBRENOME, c.NACIONALIDADE, c.CEP, c.ESTADO, c.CIDADE, c.LOGRADOURO, c.EMAIL, c.TELEFONE, c.CPF, c.ID
		FROM CLIENTES c WITH(NOLOCK)
	ELSE
		SELECT c.NOME, c.SOBRENOME, c.NACIONALIDADE, c.CEP, c.ESTADO, c.CIDADE, c.LOGRADOURO, c.EMAIL, c.TELEFONE, c.CPF, c.ID
		FROM CLIENTES c WITH(NOLOCK)
		WHERE c.ID = @ID
END
